service: serverless-rest-golang

provider:
  name: aws
  runtime: go1.x
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "s3:*"
       Resource: "*"

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  rest:
    handler: bin/rest
    events:
      - http:
          path: items
          method: any
      - http:
          path: items/{id}
          method: any

resources:
  Resources:
    restItemBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: serverless-rest-golang-items
